/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author bapna
 */
public class FrameAnimales extends javax.swing.JFrame {

// variable de seguridad para boton eliminar
private int animalIDSeleccionado = -1;
    /**
     * Creates new form FrameAnimales
     */
    public FrameAnimales() {
        initComponents();
        cargarDatosIniciales();
    }

    private void cargarDatosIniciales() {
        AnimalLoad dao = new AnimalLoad();

        // 1. Cargar datos en la JTable (jTable1)
        jTable1.setModel(dao.cargarModeloAnimales());

        // 2. Cargar datos en los ComboBox
        // Nota: Asumo que cmbEspecie es para la especie a registrar
        Vector<String> especies = dao.cargarNombresEspecies();
        cmbEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(especies));

        // Nota: Asumo que cmbHabitat es para el hábitat a registrar
        Vector<String> habitats = dao.cargarNombresHabitat();
        cmbHabitat.setModel(new javax.swing.DefaultComboBoxModel<>(habitats));

        // 3. Puedes usar cmbEspecie1 para el campo "Sexo", si es el caso, llenándolo manualmente:
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Selecciona", "M", "F"}));

        // NOTA IMPORTANTE: Si quieres que la tabla se actualice después de GUARDAR/ELIMINAR,
        // solo tienes que llamar de nuevo a este método: cargarDatosIniciales();
    }

    private void limpiarCampos() {
        // Limpiar campo de texto
        txtNombre.setText("");

        // Resetear ComboBox a la primera opción ("Selecciona")
        cmbSexo.setSelectedIndex(0); // Sexo
        cmbEspecie.setSelectedIndex(0);  // Especie
        cmbHabitat.setSelectedIndex(0);  // Hábitat

        // Opcional: Podrías resetear las fechas a la fecha actual si lo deseas, 
        // pero usualmente se dejan con la fecha seleccionada o la actual.
        // dateCFNacimineto.setCurrent(java.util.Calendar.getInstance()); 
        // dateCFRegistro.setCurrent(java.util.Calendar.getInstance());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbEspecie = new javax.swing.JComboBox<>();
        cmbHabitat = new javax.swing.JComboBox<>();
        cmbSexo = new javax.swing.JComboBox<>();
        brnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        dateCFNacimineto = new datechooser.beans.DateChooserCombo();
        dateCFRegistro = new datechooser.beans.DateChooserCombo();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("Tabla Animales BD Zoologico");
        jLabel1.setIconTextGap(8);
        jLabel1.setMaximumSize(new java.awt.Dimension(156, 666));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setText("Sexo");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("Fecha Nacimiento");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setText("FechaRegistro");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setText("Especie");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setText("Habitat");

        cmbEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));

        cmbHabitat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));

        brnGuardar.setText("Guardar");
        brnGuardar.addActionListener(this::brnGuardarActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(brnGuardar)
                            .addComponent(btnEliminar))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModificar)
                                    .addComponent(btnLimpiar))
                                .addContainerGap(190, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(dateCFRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(78, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)
                                .addComponent(dateCFNacimineto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dateCFNacimineto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dateCFRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brnGuardar)
                    .addComponent(btnModificar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void brnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnGuardarActionPerformed
        // TODO add your handling code here:
// 1. Recolección y validación de datos
        String nombre = txtNombre.getText();
        String sexo = (String) cmbSexo.getSelectedItem();
        String especieNombre = (String) cmbEspecie.getSelectedItem();
        String habitatNombre = (String) cmbHabitat.getSelectedItem();

        // Obtener la fecha del DateChooser (datechooser.beans.DateChooserCombo)
        java.util.Calendar fechaNacimiento = dateCFNacimineto.getCurrent();
        java.util.Calendar fechaRegistro = dateCFRegistro.getCurrent();

        // Validación básica
        if (nombre.isEmpty() || sexo.equals("Selecciona") || especieNombre.equals("Selecciona") || habitatNombre.equals("Selecciona")) {
            JOptionPane.showMessageDialog(this, "Todos los campos (Nombre, Sexo, Especie, Hábitat) son obligatorios.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Llamar al método de inserción del DAO
        AnimalLoad dao = new AnimalLoad();
        boolean exito = dao.insertarAnimal(nombre, sexo, fechaNacimiento, fechaRegistro, especieNombre, habitatNombre);

        // 3. Manejo de la respuesta
        if (exito) {
            JOptionPane.showMessageDialog(this, "Animal guardado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Opcional: Recargar la tabla y limpiar campos después de la inserción
            cargarDatosIniciales(); // Este método recarga la jTable1 y los combos.
            // limpiarCampos(); // (Tendrías que implementar este método)

        } else {
            JOptionPane.showMessageDialog(this, "Fallo al guardar el animal. Revisa la consola para más detalles.", "Error de Inserción", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_brnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        // 1. Verificar si se ha seleccionado alguna fila en la tabla
    int filaSeleccionada = jTable1.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, 
            "Por favor, selecciona el animal de la tabla que deseas eliminar.", 
            "Selección Requerida", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Obtener el ID del Animal de la fila seleccionada
    // El ID se encuentra en la columna 0 del modelo de la tabla.
    // Usamos getValueAt y convertimos el objeto a entero (Integer)
    int animalID = (int) jTable1.getModel().getValueAt(filaSeleccionada, 0);
    
    // 3. Confirmación del Usuario (Práctica recomendada)
    int confirmacion = JOptionPane.showConfirmDialog(this,
        "¿Estás seguro de que deseas eliminar el animal con ID: " + animalID + "?",
        "Confirmar Eliminación",
        JOptionPane.YES_NO_OPTION);
    
    if (confirmacion == JOptionPane.NO_OPTION) {
        return; // El usuario canceló la operación
    }

    // 4. Llamar al método de eliminación del DAO
    AnimalLoad dao = new AnimalLoad();
    boolean exito = dao.eliminarAnimal(animalID);

    // 5. Manejo de la respuesta
    if (exito) {
        JOptionPane.showMessageDialog(this, 
            "Animal eliminado exitosamente.", 
            "Éxito", 
            JOptionPane.INFORMATION_MESSAGE);
        
        // Recargar la tabla para reflejar el cambio
        cargarDatosIniciales();
        
    } else {
        JOptionPane.showMessageDialog(this, 
            "Fallo al eliminar el animal. Revisa la consola para más detalles.", 
            "Error de Eliminación", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
// 1. Verificar si hay un ID seleccionado desde el click de la tabla
    if (animalIDSeleccionado == -1) {
        JOptionPane.showMessageDialog(this, 
            "Debe seleccionar un animal de la tabla (haciendo clic) para modificar.", 
            "Selección Requerida", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Recolección y validación de datos
    String nombre = txtNombre.getText();
    String sexo = (String) cmbSexo.getSelectedItem();
    String especieNombre = (String) cmbEspecie.getSelectedItem();
    String habitatNombre = (String) cmbHabitat.getSelectedItem();
    java.util.Calendar fechaNacimiento = dateCFNacimineto.getCurrent();
    
    // Validación de campos obligatorios
    if (nombre.isEmpty() || sexo.equals("Selecciona") || especieNombre.equals("Selecciona") || habitatNombre.equals("Selecciona")) {
        JOptionPane.showMessageDialog(this, "Todos los campos (Nombre, Sexo, Especie, Hábitat) son obligatorios.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 3. Confirmación del Usuario (Opcional, pero buena práctica)
    int confirmacion = JOptionPane.showConfirmDialog(this,
        "¿Estás seguro de que deseas modificar el animal con ID: " + animalIDSeleccionado + "?",
        "Confirmar Modificación",
        JOptionPane.YES_NO_OPTION);
    
    if (confirmacion == JOptionPane.NO_OPTION) {
        return; // El usuario canceló la operación
    }

    // 4. Llamar al método de modificación del DAO
    AnimalLoad dao = new AnimalLoad();
    boolean exito = dao.modificarAnimal(
        animalIDSeleccionado, 
        nombre, 
        sexo, 
        fechaNacimiento, 
        especieNombre, 
        habitatNombre
    );

    // 5. Manejo de la respuesta
    if (exito) {
        JOptionPane.showMessageDialog(this, 
            "Animal modificado exitosamente.", 
            "Éxito", 
            JOptionPane.INFORMATION_MESSAGE);
        cargarDatosIniciales(); // Recargar la tabla
        limpiarCampos();        // Limpiar formulario
        animalIDSeleccionado = -1; // Resetear ID
    } else {
        JOptionPane.showMessageDialog(this, 
            "Fallo al modificar el animal. Verifique que los nombres de Especie/Hábitat existan.", 
            "Error de Modificación", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
if (evt.getClickCount() == 1) { 
        
        int fila = jTable1.getSelectedRow();
        if (fila == -1) return;
        
        try {
            // Paso 1: EXTRAER EL ID de la columna 0 de la tabla
            Object idValue = jTable1.getModel().getValueAt(fila, 0);
            animalIDSeleccionado = (idValue instanceof Integer) ? (int) idValue : Integer.parseInt(idValue.toString());
            
            if (animalIDSeleccionado == -1) return;
            
            // Paso 2: CONSULTAR LOS DATOS EXACTOS a la base de datos
            AnimalLoad dao = new AnimalLoad();
            Vector<Object> datosAnimal = dao.obtenerAnimalPorId(animalIDSeleccionado);
            
            if (datosAnimal != null && datosAnimal.size() >= 5) {
                // El orden del vector es: [0:Nombre, 1:Sexo, 2:FechaNac, 3:Especie, 4:Habitat]
                
                // 3. Cargar Nombre
                txtNombre.setText((String) datosAnimal.get(0));
                
                // 4. Cargar Sexo
                cmbSexo.setSelectedItem((String) datosAnimal.get(1)); 

                // 5. Cargar Fecha Nacimiento (Conversion robusta de java.sql.Date a Calendar)
                java.sql.Date sqlDateNac = (java.sql.Date) datosAnimal.get(2);
                java.util.Calendar calNac = java.util.Calendar.getInstance();
                calNac.setTime(sqlDateNac);
                dateCFNacimineto.setCurrent(calNac);
                
                // 6. Cargar Especie
                cmbEspecie.setSelectedItem((String) datosAnimal.get(3));

                // 7. Cargar Hábitat
                cmbHabitat.setSelectedItem((String) datosAnimal.get(4));
                
                System.out.println("✅ Datos del Animal ID " + animalIDSeleccionado + " cargados desde DB.");
                
            } else {
                JOptionPane.showMessageDialog(this, 
                    "No se pudieron obtener los detalles del animal desde la base de datos.",
                    "Error de Carga", 
                    JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error grave al procesar la selección: " + e.getMessage(),
                "Error de Carga", 
                JOptionPane.ERROR_MESSAGE);
            System.err.println("Error en jTable1MouseClicked: " + e.getMessage());
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameAnimales().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnGuardar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbEspecie;
    private javax.swing.JComboBox<String> cmbHabitat;
    private javax.swing.JComboBox<String> cmbSexo;
    private datechooser.beans.DateChooserCombo dateCFNacimineto;
    private datechooser.beans.DateChooserCombo dateCFRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
