package ZoologicoAppU6;

import java.awt.Color;
import java.awt.Component;
import java.awt.Point;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class FrameAnimales extends javax.swing.JFrame {
    private int animalIDSeleccionado = -1;
    private Component parentComponent;
    QueryLoaderScript dao;
    private Map<String, String> especiesMap, habitatsMap;

    public FrameAnimales(Component parentComponent) {
        initComponents();
        cargarDatosIniciales();
        
        setBackground(new Color(0, 0, 0, 0));
        
        setLocationRelativeTo(parentComponent);
        this.parentComponent = parentComponent;
    }

    private void cargarDatosIniciales() {
        dao = new QueryLoaderScript();
        
        // Cargar datos en la JTable (jTable1)
        jTable1.setModel(dao.CargarModeloDinamico("Animales"));

        // Cargar datos en los ComboBox;
        Vector<String> especies = new Vector<String>();
        Vector<String> habitats = new Vector<String>();
        
        especies.add("Seleccionar...");
        especies.addAll(dao.CargarSeleccionDinamica("Especies", "NombreEspecie"));
        cmbEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(especies));
        cmbEspecieFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(especies));

        habitats.add("Seleccionar...");
        habitats.addAll(dao.CargarSeleccionDinamica("Habitat", "NombreHabitat"));
        cmbHabitat.setModel(new javax.swing.DefaultComboBoxModel<>(habitats));
        cmbHabitatFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(habitats));
        
        // Puedes usar cmbEspecie1 para el campo "Sexo", si es el caso, llenándolo manualmente:
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Seleccionar...", "M", "F"}));
        cmbSexoFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Seleccionar...", "M", "F"}));
        
        Vector<String> especiesID = new Vector<String>(dao.CargarSeleccionDinamica("Especies", "idEspecie"));
        Vector<String> habitatsID = new Vector<String>(dao.CargarSeleccionDinamica("Habitat", "idHabitat"));
        
        especiesMap = new HashMap();
        habitatsMap = new HashMap();
        
        for (int i = 0; i < especiesID.size(); i++) {
            String id = especiesID.get(i);
            String nombre = especies.get(i + 1);
            especiesMap.put(nombre, id);
        }
        for (int i = 0; i < habitatsID.size(); i++) {
            String id = habitatsID.get(i);
            String nombre = habitats.get(i + 1);
            habitatsMap.put(nombre, id);
        }
    }

    private void limpiarCampos() {
        // Limpiar campo de texto
        txtNombre.setText("");

        // Resetear ComboBox a la primera opción ("Selecciona")
        cmbSexo.setSelectedIndex(0); // Sexo
        cmbEspecie.setSelectedIndex(0);  // Especie
        cmbHabitat.setSelectedIndex(0);  // Hábitat

        // Resetear las fechas a la fecha actual
        dateCFNacimiento.setCurrent(java.util.Calendar.getInstance()); 
        dateCFRegistro.setCurrent(java.util.Calendar.getInstance());
    }
    private void llenarCampos(List<Object> values) {
        // Limpiar campo de texto
        txtNombre.setText(values.get(2).toString());

        // Seleccionar los valores de los ComboBox
        cmbSexo.setSelectedItem(values.get(3).toString()); 
        cmbEspecie.setSelectedItem(values.get(1).toString());  // Especie
        cmbHabitat.setSelectedItem(values.get(6).toString());  // Hábitat

        // Resetear las fechas a la fecha actual
        dateCFNacimiento.setCurrent(java.util.Calendar.getInstance()); 
        dateCFRegistro.setCurrent(java.util.Calendar.getInstance());

        java.sql.Date sqlDateReg = (java.sql.Date) values.get(4);
        java.util.Calendar calReg = java.util.Calendar.getInstance();
        if(sqlDateReg != null) calReg.setTime(sqlDateReg);
        else calReg.setTime(new java.util.Date());
        dateCFRegistro.setCurrent(calReg);
        dateCFRegistro.setSelectedDate(calReg);

        java.sql.Date sqlDateNac = (java.sql.Date) values.get(5);
        java.util.Calendar calNac = java.util.Calendar.getInstance();
        if(sqlDateNac != null) calNac.setTime(sqlDateNac);
        else calNac.setTime(new java.util.Date());
        dateCFNacimiento.setCurrent(calNac);
        dateCFNacimiento.setSelectedDate(calNac);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelShadow1 = new ZoologicoAppU6.PanelShadow();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        dateCFNacimiento = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        dateCFRegistro = new datechooser.beans.DateChooserCombo();
        jLabel6 = new javax.swing.JLabel();
        cmbEspecie = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbHabitat = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreFiltro = new javax.swing.JTextField();
        cmbSexoFiltro = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbEspecieFiltro = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbHabitatFiltro = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        brnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(960, 720));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(960, 720));
        setResizable(false);

        panelShadow1.setShadowSize(15);
        panelShadow1.setLayout(new java.awt.GridBagLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 44, 107)));
        jPanel9.setMinimumSize(new java.awt.Dimension(960, 720));
        jPanel9.setPreferredSize(new java.awt.Dimension(940, 700));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 44, 107));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(603, 48));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Corbel Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tabla Animales BD Zoologico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 0, 16);
        jPanel7.add(jLabel1, gridBagConstraints);

        jPanel1.add(jPanel7, java.awt.BorderLayout.WEST);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(39, 82, 185));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("←");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        jPanel8.add(jButton1, gridBagConstraints);

        jPanel1.add(jPanel8, java.awt.BorderLayout.EAST);

        jPanel9.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel4.setPreferredSize(new java.awt.Dimension(720, 400));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(300, 230));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 230));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(txtNombre, gridBagConstraints);

        jLabel3.setText("Sexo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(jLabel3, gridBagConstraints);

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(cmbSexo, gridBagConstraints);

        jLabel4.setText("Fecha Nacimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(dateCFNacimiento, gridBagConstraints);

        jLabel5.setText("Fecha Registro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(dateCFRegistro, gridBagConstraints);

        jLabel6.setText("Especie");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(jLabel6, gridBagConstraints);

        cmbEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(cmbEspecie, gridBagConstraints);

        jLabel7.setText("Habitat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(jLabel7, gridBagConstraints);

        cmbHabitat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(cmbHabitat, gridBagConstraints);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel10.setLayout(new java.awt.GridBagLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel8.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel11.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel11.add(txtNombreFiltro, gridBagConstraints);

        cmbSexoFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel11.add(cmbSexoFiltro, gridBagConstraints);

        jLabel9.setText("Sexo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel11.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Especie");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel11.add(jLabel10, gridBagConstraints);

        cmbEspecieFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        cmbEspecieFiltro.addActionListener(this::cmbEspecieFiltroActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel11.add(cmbEspecieFiltro, gridBagConstraints);

        jLabel11.setText("Habitat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel11.add(jLabel11, gridBagConstraints);

        cmbHabitatFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel11.add(cmbHabitatFiltro, gridBagConstraints);

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(this::btnFiltrarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel11.add(btnFiltrar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel10.add(jPanel11, gridBagConstraints);

        jPanel2.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        brnGuardar.setText("Guardar");
        brnGuardar.addActionListener(this::brnGuardarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel6.add(brnGuardar, gridBagConstraints);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel6.add(btnModificar, gridBagConstraints);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel6.add(btnLimpiar, gridBagConstraints);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel6.add(btnEliminar, gridBagConstraints);

        jPanel2.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel4.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel4, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelShadow1.add(jPanel9, gridBagConstraints);

        getContentPane().add(panelShadow1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void brnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnGuardarActionPerformed
        // Recolección y validación de datos
        String nombre = txtNombre.getText();
        String sexo = (String) cmbSexo.getSelectedItem();
        
        int especieID = Integer.parseInt(especiesMap.get(cmbEspecie.getSelectedItem().toString()));
        int habitatID = Integer.parseInt(habitatsMap.get(cmbHabitat.getSelectedItem().toString()));

        // Obtener la fecha del DateChooser (datechooser.beans.DateChooserCombo)
        java.sql.Date fechaRegistro = new java.sql.Date(dateCFRegistro.getCurrent().getTime().getTime());
        java.sql.Date fechaNacimiento = new java.sql.Date(dateCFNacimiento.getCurrent().getTime().getTime());

        // Validación básica
        if (nombre.isEmpty() || sexo.equals("Selecciona") || cmbEspecie.getSelectedIndex() == -1 || cmbHabitat.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Todos los campos (Nombre, Sexo, Especie, Hábitat) son obligatorios.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        List<Object> values = new ArrayList<Object>();
            values.add(especieID);
            values.add(nombre);
            values.add(sexo);
            values.add(fechaRegistro);
            values.add(fechaNacimiento);
            values.add(habitatID);

        // Llamar al método de inserción del DAO
        boolean exito = dao.InsertIntoTable("Animales", values);

        // Manejo de la respuesta
        if (exito) {
            JOptionPane.showMessageDialog(this, "Animal guardado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            cargarDatosIniciales();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Fallo al guardar el animal. Revisa la consola para más detalles.", "Error de Inserción", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_brnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Verificar si se ha seleccionado alguna fila en la tabla
        int filaSeleccionada = jTable1.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, selecciona el animal de la tabla que deseas eliminar.", 
                "Selección Requerida", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Obtener el ID del Animal de la fila seleccionada
        // El ID se encuentra en la columna 0 del modelo de la tabla.
        // Usamos getValueAt y convertimos el objeto a entero (Integer)
        Object idValue = jTable1.getModel().getValueAt(filaSeleccionada, 0);
        int animalID = (idValue instanceof Integer) ? (int) idValue : Integer.parseInt(idValue.toString());

        if (animalID == -1) return;

        // Confirmación del Usuario (Práctica recomendada)
        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Estás seguro de que deseas eliminar el animal con ID: " + animalID + "?",
            "Confirmar Eliminación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacion != JOptionPane.YES_OPTION)
            return; // El usuario canceló la operación

        // Llamar al método de eliminación del DAO
        boolean exito = dao.DeleteFromTable("Animales", animalID);

        // Manejo de la respuesta
        if (exito) {
            JOptionPane.showMessageDialog(this, 
                "Animal eliminado exitosamente.", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE
            );
            // Recargar la tabla para reflejar el cambio
            cargarDatosIniciales();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Fallo al eliminar el animal. Revisa la consola para más detalles.", 
                "Error de Eliminación", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // Verificar si se ha seleccionado alguna fila en la tabla
        int filaSeleccionada = jTable1.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, 
                "Debe seleccionar un animal de la tabla (haciendo clic) para modificar.", 
                "Selección Requerida", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        Object idValue = jTable1.getModel().getValueAt(filaSeleccionada, 0);
        int animalID = (idValue instanceof Integer) ? (int) idValue : Integer.parseInt(idValue.toString());
                                   
        // Recolección y validación de datos
        String nombre = txtNombre.getText();
        String sexo = (String) cmbSexo.getSelectedItem();
        
        int especieID = Integer.parseInt(especiesMap.get(cmbEspecie.getSelectedItem().toString()));
        int habitatID = Integer.parseInt(habitatsMap.get(cmbHabitat.getSelectedItem().toString()));

        // Obtener la fecha del DateChooser (datechooser.beans.DateChooserCombo)
        java.sql.Date fechaRegistro = new java.sql.Date(dateCFRegistro.getCurrent().getTime().getTime());
        java.sql.Date fechaNacimiento = new java.sql.Date(dateCFNacimiento.getCurrent().getTime().getTime());

        // Validación básica
        if (nombre.isEmpty() || sexo.equals("Selecciona") || cmbEspecie.getSelectedIndex() == -1 || cmbHabitat.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Todos los campos (Nombre, Sexo, Especie, Hábitat) son obligatorios.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Confirmación del Usuario (Opcional, pero buena práctica)
        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Estás seguro de que deseas modificar el animal con ID: " + animalID + "?",
            "Confirmar Modificación",
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.NO_OPTION)
            return; // El usuario canceló la operación

        List<Object> values = new ArrayList<Object>();
            values.add(especieID);
            values.add(nombre);
            values.add(sexo);
            values.add(fechaRegistro);
            values.add(fechaNacimiento);
            values.add(habitatID);

        // Llamar al método de modificación del DAO
        boolean exito = dao.ModifyFromTable("Animales", animalID, values);

        // 5. Manejo de la respuesta
        if (exito) {
            JOptionPane.showMessageDialog(this, 
                "Animal modificado exitosamente.", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            cargarDatosIniciales(); // Recargar la tabla
            limpiarCampos();        // Limpiar formulario
        } else {
            JOptionPane.showMessageDialog(this, 
                "Fallo al modificar el animal. Verifique que los nombres de Especie/Hábitat existan.", 
                "Error de Modificación", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) { 

            int fila = jTable1.getSelectedRow();
            if (fila == -1) return;

            try {
                Object idValue = jTable1.getModel().getValueAt(fila, 0);
                animalIDSeleccionado = (idValue instanceof Integer) ? (int) idValue : Integer.parseInt(idValue.toString());

                if (animalIDSeleccionado == -1) return;
                
                List<Object> datosAnimal = dao.GetFromIdentifier("Animales", animalIDSeleccionado);
                if (datosAnimal != null) {
                    llenarCampos(datosAnimal);
                    System.out.println("Datos del Animal ID " + animalIDSeleccionado + " cargados desde DB.");
                } else
                    System.err.print("No se pudieron obtener los detalles del animal desde la base de datos.");
            } catch (Exception e) {
                System.err.print("Error grave al procesar la seleccion, en jTable1MouseClicked: ");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked
    
    final Point clickPoint = new Point();

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

        clickPoint.x = evt.getX();
        clickPoint.y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen() - clickPoint.x - 10;
        int y = evt.getYOnScreen() - clickPoint.y - 10;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        parentComponent.setEnabled(true);
        parentComponent.setLocation(getLocation());
        parentComponent.setVisible(true);
        dispose();
        ((JFrame)parentComponent).toFront();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static String normalizeForRegex(String input) {
        if (input == null) return "";
        // Normalize to NFD form and strip diacritical marks
        String normalized = Normalizer.normalize(input, Normalizer.Form.NFD)
                                       .replaceAll("\\p{M}", "");
        return normalized;
    }

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        TableModel model = jTable1.getModel();
        
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) model);
        jTable1.setRowSorter(sorter);

        String nombre = normalizeForRegex(txtNombreFiltro.getText());
        String sexo = cmbSexoFiltro.getSelectedItem().toString();
        String especie = cmbEspecieFiltro.getSelectedItem().toString();
        String habitat = cmbHabitatFiltro.getSelectedItem().toString();
        
        // Create individual filters
        RowFilter<DefaultTableModel, Object> speciesFilter = RowFilter.regexFilter("(?i)" + especie, 1);
        RowFilter<DefaultTableModel, Object> sexFilter     = RowFilter.regexFilter("(?i)" + sexo, 3);
        RowFilter<DefaultTableModel, Object> habitatFilter = RowFilter.regexFilter("(?i)" + habitat, 6);
        RowFilter<DefaultTableModel, Object> nameFilter    = RowFilter.regexFilter("(?i)" + nombre, 2);

        // Combine them with AND logic
        List<RowFilter<DefaultTableModel, Object>> filters = new ArrayList<>();
        if (cmbEspecieFiltro.getSelectedIndex() != 0) filters.add(speciesFilter);
        if (cmbSexoFiltro.getSelectedIndex() != 0) filters.add(sexFilter);
        if (cmbHabitatFiltro.getSelectedIndex() != 0) filters.add(habitatFilter);
        if (!nombre.isBlank()) filters.add(nameFilter);
        
        RowFilter<DefaultTableModel, Object> combinedFilter = RowFilter.andFilter(filters);
        sorter.setRowFilter(combinedFilter);
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void cmbEspecieFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEspecieFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEspecieFiltroActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new FrameAnimales().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnGuardar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbEspecie;
    private javax.swing.JComboBox<String> cmbEspecieFiltro;
    private javax.swing.JComboBox<String> cmbHabitat;
    private javax.swing.JComboBox<String> cmbHabitatFiltro;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JComboBox<String> cmbSexoFiltro;
    private datechooser.beans.DateChooserCombo dateCFNacimiento;
    private datechooser.beans.DateChooserCombo dateCFRegistro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private ZoologicoAppU6.PanelShadow panelShadow1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreFiltro;
    // End of variables declaration//GEN-END:variables
}
