package ZoologicoAppU6;

import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class FrameMain extends javax.swing.JFrame {
    private int animalIDSeleccionado = -1;
    QueryLoaderScript dao;

    public FrameMain() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        
        setLocationRelativeTo(null);
        //new Login(this).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelShadow1 = new ZoologicoAppU6.PanelShadow();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnTablaAnimales = new javax.swing.JButton();
        btnTablaEspecies = new javax.swing.JButton();
        btnTablaEspecies1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(960, 720));
        setUndecorated(true);
        setResizable(false);

        panelShadow1.setShadowSize(15);
        panelShadow1.setLayout(new java.awt.GridBagLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 44, 107)));
        jPanel9.setMinimumSize(new java.awt.Dimension(960, 720));
        jPanel9.setPreferredSize(new java.awt.Dimension(940, 700));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 44, 107));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(603, 48));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Corbel Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tablas BD Zoologico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 0, 16);
        jPanel7.add(jLabel1, gridBagConstraints);

        jPanel1.add(jPanel7, java.awt.BorderLayout.WEST);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(185, 40, 40));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        jPanel8.add(jButton1, gridBagConstraints);

        jPanel1.add(jPanel8, java.awt.BorderLayout.EAST);

        jPanel9.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel4.setPreferredSize(new java.awt.Dimension(720, 400));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(300, 230));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 230));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        btnTablaAnimales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTablaAnimales.setText("Tabla Animales");
        btnTablaAnimales.addActionListener(this::btnTablaAnimalesActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(btnTablaAnimales, gridBagConstraints);

        btnTablaEspecies.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTablaEspecies.setText("Tabla Especies");
        btnTablaEspecies.addActionListener(this::btnTablaEspeciesActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(btnTablaEspecies, gridBagConstraints);

        btnTablaEspecies1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTablaEspecies1.setText("Tabla Habitat");
        btnTablaEspecies1.addActionListener(this::btnTablaEspecies1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(btnTablaEspecies1, gridBagConstraints);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Usuario: Zoo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        jPanel10.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Password: Zoo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        jPanel10.add(jLabel3, gridBagConstraints);

        jPanel6.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel4, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelShadow1.add(jPanel9, gridBagConstraints);

        getContentPane().add(panelShadow1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    final Point clickPoint = new Point();

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

        clickPoint.x = evt.getX();
        clickPoint.y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen() - clickPoint.x - 10;
        int y = evt.getYOnScreen() - clickPoint.y - 10;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTablaAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaAnimalesActionPerformed
        setEnabled(false);
        new FrameAnimales(this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnTablaAnimalesActionPerformed

    private void btnTablaEspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaEspeciesActionPerformed
        setEnabled(false);
        new FrameEspecies(this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnTablaEspeciesActionPerformed

    private void btnTablaEspecies1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaEspecies1ActionPerformed
        setEnabled(false);
        new FrameHabitats(this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnTablaEspecies1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new FrameAnimales().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTablaAnimales;
    private javax.swing.JButton btnTablaEspecies;
    private javax.swing.JButton btnTablaEspecies1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private ZoologicoAppU6.PanelShadow panelShadow1;
    // End of variables declaration//GEN-END:variables
}
