package ZoologicoAppU6;

import java.awt.Color;
import java.awt.Component;
import java.awt.Point;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class FrameHabitats extends javax.swing.JFrame {
    private int animalIDSeleccionado = -1;
    private Component parentComponent;
    QueryLoaderScript dao;


    public FrameHabitats(Component parentComponent) {
        initComponents();
        
        cargarDatosIniciales();
        setBackground(new Color(0, 0, 0, 0));
        
        setLocationRelativeTo(parentComponent);
        this.parentComponent = parentComponent;
    }

    private void cargarDatosIniciales() {
        dao = new QueryLoaderScript();
        
        // Cargar datos en la JTable (jTable1)
        jTable1.setModel(dao.CargarModeloDinamico("Habitat"));
    }

    private void limpiarCampos() {
        // Limpiar campo de texto
        txtNombre.setText("");
    }
    private void llenarCampos(List<Object> values) {
        // Limpiar campo de texto
        txtNombre.setText(values.get(1).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelShadow1 = new ZoologicoAppU6.PanelShadow();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreFiltro = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        brnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(960, 720));
        setUndecorated(true);
        setResizable(false);

        panelShadow1.setShadowSize(15);
        panelShadow1.setLayout(new java.awt.GridBagLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 44, 107)));
        jPanel9.setMinimumSize(new java.awt.Dimension(960, 720));
        jPanel9.setPreferredSize(new java.awt.Dimension(940, 700));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 44, 107));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(603, 48));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Corbel Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tabla Habitats BD Zoologico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 0, 16);
        jPanel7.add(jLabel1, gridBagConstraints);

        jPanel1.add(jPanel7, java.awt.BorderLayout.WEST);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(39, 82, 185));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("←");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        jPanel8.add(jButton1, gridBagConstraints);

        jPanel1.add(jPanel8, java.awt.BorderLayout.EAST);

        jPanel9.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel4.setPreferredSize(new java.awt.Dimension(720, 400));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(300, 230));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 230));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel5.add(txtNombre, gridBagConstraints);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel10.setLayout(new java.awt.GridBagLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel8.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel11.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel11.add(txtNombreFiltro, gridBagConstraints);

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(this::btnFiltrarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel11.add(btnFiltrar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel10.add(jPanel11, gridBagConstraints);

        jPanel2.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        brnGuardar.setText("Guardar");
        brnGuardar.addActionListener(this::brnGuardarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel6.add(brnGuardar, gridBagConstraints);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel6.add(btnModificar, gridBagConstraints);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel6.add(btnLimpiar, gridBagConstraints);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel6.add(btnEliminar, gridBagConstraints);

        jPanel2.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel4.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel4, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelShadow1.add(jPanel9, gridBagConstraints);

        getContentPane().add(panelShadow1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void brnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnGuardarActionPerformed
        // Recolección y validación de datos
        String nombre = txtNombre.getText();
        
        // Validación básica
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos (Nombre) son obligatorios.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        List<Object> values = new ArrayList<Object>();
            values.add(nombre);

        // Llamar al método de inserción del DAO
        boolean exito = dao.InsertIntoTable("Habitat", values);

        // Manejo de la respuesta
        if (exito) {
            JOptionPane.showMessageDialog(this, "Habitat guardado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            cargarDatosIniciales();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Fallo al guardar la habitat. Revisa la consola para más detalles.", "Error de Inserción", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_brnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Verificar si se ha seleccionado alguna fila en la tabla
        int filaSeleccionada = jTable1.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, selecciona el habitat de la tabla que deseas eliminar.", 
                "Selección Requerida", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Obtener el ID del Animal de la fila seleccionada
        // El ID se encuentra en la columna 0 del modelo de la tabla.
        // Usamos getValueAt y convertimos el objeto a entero (Integer)
        Object idValue = jTable1.getModel().getValueAt(filaSeleccionada, 0);
        int animalID = (idValue instanceof Integer) ? (int) idValue : Integer.parseInt(idValue.toString());

        if (animalID == -1) return;

        // Confirmación del Usuario (Práctica recomendada)
        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Estás seguro de que deseas eliminar la habitat con ID: " + animalID + "?",
            "Confirmar Eliminación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacion != JOptionPane.YES_OPTION)
            return; // El usuario canceló la operación

        // Llamar al método de eliminación del DAO
        boolean exito = dao.DeleteFromTable("Habitat", animalID);

        // Manejo de la respuesta
        if (exito) {
            JOptionPane.showMessageDialog(this, 
                "Habitat eliminado exitosamente.", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE
            );
            // Recargar la tabla para reflejar el cambio
            cargarDatosIniciales();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Fallo al eliminar el habitat. Revisa la consola para más detalles.", 
                "Error de Eliminación", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // Verificar si se ha seleccionado alguna fila en la tabla
        int filaSeleccionada = jTable1.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, 
                "Debe seleccionar un habitat de la tabla (haciendo clic) para modificar.", 
                "Selección Requerida", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        Object idValue = jTable1.getModel().getValueAt(filaSeleccionada, 0);
        int animalID = (idValue instanceof Integer) ? (int) idValue : Integer.parseInt(idValue.toString());
                                   
        // Recolección y validación de datos
        String nombre = txtNombre.getText();
        
        // Validación básica
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos (Nombre) son obligatorios.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        // Confirmación del Usuario (Opcional, pero buena práctica)
        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Estás seguro de que deseas modificar la habitat con ID: " + animalID + "?",
            "Confirmar Modificación",
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.NO_OPTION)
            return; // El usuario canceló la operación

        List<Object> values = new ArrayList<Object>();
            values.add(nombre);

        // Llamar al método de modificación del DAO
        boolean exito = dao.ModifyFromTable("Habitat", animalID, values);

        // 5. Manejo de la respuesta
        if (exito) {
            JOptionPane.showMessageDialog(this, 
                "Habitat modificado exitosamente.", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            cargarDatosIniciales(); // Recargar la tabla
            limpiarCampos();        // Limpiar formulario
        } else {
            JOptionPane.showMessageDialog(this, 
                "Fallo al modificar el habitat.", 
                "Error de Modificación", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) { 

            int fila = jTable1.getSelectedRow();
            if (fila == -1) return;

            try {
                Object idValue = jTable1.getModel().getValueAt(fila, 0);
                animalIDSeleccionado = (idValue instanceof Integer) ? (int) idValue : Integer.parseInt(idValue.toString());

                if (animalIDSeleccionado == -1) return;
                
                List<Object> datosAnimal = dao.GetFromIdentifier("Habitat", animalIDSeleccionado);
                if (datosAnimal != null) {
                    llenarCampos(datosAnimal);
                    System.out.println("Datos del Habitat ID " + animalIDSeleccionado + " cargados desde DB.");
                } else
                    System.err.print("No se pudieron obtener los detalles de la habitat desde la base de datos.");
            } catch (Exception e) {
                System.err.print("Error grave al procesar la seleccion, en jTable1MouseClicked: ");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked
    
    final Point clickPoint = new Point();

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

        clickPoint.x = evt.getX();
        clickPoint.y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen() - clickPoint.x - 10;
        int y = evt.getYOnScreen() - clickPoint.y - 10;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        parentComponent.setEnabled(true);
        parentComponent.setLocation(getLocation());
        parentComponent.setVisible(true);
        dispose();
        ((JFrame)parentComponent).toFront();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static String normalizeForRegex(String input) {
        if (input == null) return "";
        // Normalize to NFD form and strip diacritical marks
        String normalized = Normalizer.normalize(input, Normalizer.Form.NFD)
                                       .replaceAll("\\p{M}", "");
        return normalized;
    }

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        TableModel model = jTable1.getModel();
        
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) model);
        jTable1.setRowSorter(sorter);

        String nombre = normalizeForRegex(txtNombreFiltro.getText());
        
        // Create individual filters
        RowFilter<DefaultTableModel, Object> nameFilter    = RowFilter.regexFilter("(?i)" + nombre, 1);

        // Combine them with AND logic
        List<RowFilter<DefaultTableModel, Object>> filters = new ArrayList<>();
        if (!nombre.isBlank()) filters.add(nameFilter);
        
        RowFilter<DefaultTableModel, Object> combinedFilter = RowFilter.andFilter(filters);
        sorter.setRowFilter(combinedFilter);
    }//GEN-LAST:event_btnFiltrarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new FrameAnimales().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnGuardar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private ZoologicoAppU6.PanelShadow panelShadow1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreFiltro;
    // End of variables declaration//GEN-END:variables
}
